FROM public.ecr.aws/docker/library/alpine:latest

RUN apk add --no-cache \
    bash \
    curl \
    docker-cli \
    docker-cli-compose \
    docker-cli-buildx \
    git \
    jq \
    libc6-compat \
    openssh-client \
    perl \
    py-pip \
    rsync \
    run-parts \
    su-exec \
    tini \
    tini-static \
    tzdata

COPY docker-compose /usr/local/bin/docker-compose
