env:
  AGENT_BUILDERS_QUEUE: "${AGENT_BUILDERS_QUEUE:-elastic-builders}"

anchor_1: &generate-variant-group
  agents:
    queue: $AGENT_BUILDERS_QUEUE
  command: ".buildkite/steps/generate-variant-group-yml.sh '{{matrix}}' | buildkite-agent pipeline upload"
  matrix:
    setup:
      - "alpine"
      - "alpine-k8s"
      - "ubuntu-focal"
      - "ubuntu-jammy"
      - "ubuntu-jammy-hosted"
      - "ubuntu-noble"
      - "ubuntu-noble-hosted"
      - "ubuntu-resolute"

steps:
  - branches: "main"
    <<: *generate-variant-group
    label: ":pipeline: Upload {{matrix}} group (main)"

  - branches: "!main"
    <<: *generate-variant-group
    label: ":pipeline: Upload {{variant}} group (branch)"
    env:
      PUSH_IMAGE: "false"
